### PR TITLE
fixed a memory leak in build_exposed_method

### PR DESCRIPTION
**Pull request by markwellis**
the weaken was before the method was called, which meant it was copied
and no longer a weak reference

also deleted Makefile which shouldn't have been checked in (and added to gitignore)

### CODE REVIEW

**Comment by markwellis** [comment]
bump

**Comment by markwellis** [comment]
bump?

**Comment by markwellis** [comment]
any chance on merging and releasing this @lestrrat , or if you have no time/energy you can give me comaint and I'll do it?

**Comment by lestrrat** [comment]
Sorry, Inbox just keeps eating up some of my github notifications...

**Comment by lestrrat** [comment]
For whatever reason, unnecessary files such as Makefile are being edited (actually, why the fuck is it in the repo? Silly me), so I'm going to clean things up and apply your changes in a separate PR. just a sec please...

**Comment by lestrrat** [comment]
Changes from this PR were applied as #23. Closing

**Pull request closed without merging**
